config/routes.rb
Rails.application.routes.draw do

	root "welcome#index"

	resources :users
	resources :sessions

  	namespace :admin do
    	root "users#index"

    	resources :users do
			collection do
				get :search
			end
		end
  	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord

    validates :username, presence: { message: "用户名不能为空" }
    validates :username, uniqueness: { message: "用户名已存在" }
    validates :password, presence: { message: "密码不能为空" }
    validates :password, length: { minimum: 6, message: "密码长度最短为6位" }

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

    layout "admin"
    
    def index
        @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10).order("id desc")
    end

    def search
        @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10).order("id desc").where(["username like ?", "%#{params[:username]}%"])
    
        render action: :index
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
      
  end
  
  def create
    @user = User.find_by(username: params[:username], password: params[:password])
    if @user
      session[:user_id] = @user.id
      flash[:notice] = "登录成功"
      redirect_to root_path
    else
      flash[:notice] = "用户名或密码不正确"
      render action: :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:notice] = "退出成功"
    redirect_to root_path
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :auth_user, only: [:index]

    def index
        @users = User.page(params[:page] || 1).per_page(params[:per_page] || 10).order("id desc")
    end

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_attr)
        if @user.save
            flash[:notice] = "注册成功，请登录"
            redirect_to new_session_path
        else
            render action: :new
        end
    end
    
    private
    def auth_user
        unless session[:user_id]
            flash[:notice] = "请登录"
            redirect_to new_session_path
        end
    end
    
    def user_attr
        params.require(:user).permit(:username, :password)
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = if session[:user_id]
      User.find session[:user_id]
    else
      nil
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/_one_user.html.erb
<tr>
    <td><%= user.id %></td>
    <td><%= user.username %></td>
    <td></td>
</tr>

app/views/admin/users/index.html.erb
<h1>管理后台 - 用户列表</h1>

<div class="row">
  <div class="col-sm-12">

	<form action="<%= search_admin_users_path %>" method="get">
		用户名： <input type="text" name="username" value="<%= params[:username] %>" />
		<input type="submit" name="搜索">
	</form>

    <table class="table">
		<tr>
			<th>ID</th>
			<th>用户名</th>
			<th></th>
		</tr>

		<%= render partial: "one_user", collection: @users, as: :user %>
    </table>

    <%= will_paginate @users %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Circles 后台管理</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header name="top">
      <nav class="navbar navbar-default navbar-fixed-top nav-color" role="navigation" id="nav">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header nav-color">
            <button id="nav_collapse" type="button" class="navbar-toggle toggle-btn" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1">
              <span class="fa fa-bars fa-lg"></span>
            </button>
            <a class="navbar-brand custom-logo-link" href="/">
              Circles 后台管理
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-submenu-color collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right custom">
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="<%= admin_users_path %>">用户管理</a>
              </li>

              <% if session[:user_id] %>
                <li><%= link_to "#{User.find(session[:user_id]).username}, 退出", session_path(session[:user_id]), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></li>
              <% else %>
                <li><%= link_to "登录", new_session_path %></li>
              <% end -%>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-->
      </nav>
    </header>

    <div class="container body-offset">
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end -%>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Circles</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header name="top">
      <nav class="navbar navbar-default navbar-fixed-top nav-color" role="navigation" id="nav">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header nav-color">
            <button id="nav_collapse" type="button" class="navbar-toggle toggle-btn" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-controls="bs-navbar-collapse-1">
              <span class="fa fa-bars fa-lg"></span>
            </button>
            <a class="navbar-brand custom-logo-link" href="/">
              Circles
            </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-submenu-color collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right custom">
              <li>
                <a href="/">Home</a>
              </li>
              <li>
                <a href="<%= users_path %>">用户</a>
              </li>

              <% if session[:user_id] %>
                <li><%= link_to "#{User.find(session[:user_id]).username}, 退出", session_path(session[:user_id]), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></li>
              <% else %>
                <li><%= link_to "登录", new_session_path %></li>
              <% end -%>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-->
      </nav>
    </header>

    <div class="container body-offset">
      <% if flash[:notice] %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end -%>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>用户列表</h1>

<div class="row">
  <div class="col-sm-12">
    <table class="table">
      <tr>
        <th>ID</th>
        <th>用户名</th>
        <th></th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.username %></td>
          <td></td>
        </tr>
      <% end -%>
    </table>

    <%= will_paginate @users %>
  </div>
</div>

app/views/users/new.html.erb
<h1>用户注册</h1>

<div class="row">
  <div class="col-sm-5">
    <%= form_for @user, url: users_path, method: :post do |f| %>
      <div class="form-group">
        <ul class="list-unstyled">
          <% @user.errors.messages.values.flatten.each do |error| %>
            <li><i class="fa fa-exclamation-circle"></i> <%= error %></li>
          <% end -%>
        </ul>
      </div>

      <div class="form-group">
        <%= f.text_field :username, class: "form-control", placeholder: "用户名" %>
      </div>

      <div class="form-group">
        <%= f.password_field :password, class: "form-control", placeholder: "密码" %>
      </div>

      <%= f.submit "注册", class: "btn btn-primary" %> 
      <%= link_to "登录", new_session_path %>
    <% end -%>
  </div>

  <div class="col-sm-7">
  </div>
</div>

app/views/welcome/index.html.erb
<% if @user %>
  <h1>欢迎你, <%= @user.username %></h1>
<% else %>
  <h1>Circles 首页</h1>
  <p>
    
  </p>  
<% end -%>